//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurtVerheyenRechtenProject.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KurtVerheyenRechtenProject.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Groups.
        /// </summary>
        internal static string D_Groups {
            get {
                return ResourceManager.GetString("D_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Permission.
        /// </summary>
        internal static string D_Permission {
            get {
                return ResourceManager.GetString("D_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Users.
        /// </summary>
        internal static string D_Users {
            get {
                return ResourceManager.GetString("D_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Groups.
        /// </summary>
        internal static string I_Groups {
            get {
                return ResourceManager.GetString("I_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Permissions.
        /// </summary>
        internal static string I_Permissions {
            get {
                return ResourceManager.GetString("I_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Users.
        /// </summary>
        internal static string I_Users {
            get {
                return ResourceManager.GetString("I_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_GetAllPermissions.
        /// </summary>
        internal static string S_GetAllPermissions {
            get {
                return ResourceManager.GetString("S_GetAllPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Groups.
        /// </summary>
        internal static string S_Groups {
            get {
                return ResourceManager.GetString("S_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_GetAllPermissionsByGroupId.
        /// </summary>
        internal static string S_PermissionsByGroupID {
            get {
                return ResourceManager.GetString("S_PermissionsByGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_GetAllPermissionsByGroupIdItemName.
        /// </summary>
        internal static string S_PermissionsByGroupIdItemName {
            get {
                return ResourceManager.GetString("S_PermissionsByGroupIdItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Users.
        /// </summary>
        internal static string S_Users {
            get {
                return ResourceManager.GetString("S_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Group.
        /// </summary>
        internal static string U_Groups {
            get {
                return ResourceManager.GetString("U_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Permission.
        /// </summary>
        internal static string U_Permission {
            get {
                return ResourceManager.GetString("U_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_user.
        /// </summary>
        internal static string U_Users {
            get {
                return ResourceManager.GetString("U_Users", resourceCulture);
            }
        }
    }
}
